//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""8df4591d-8075-47ad-bf27-d8579d921f07"",
            ""actions"": [
                {
                    ""name"": ""P1Move"",
                    ""type"": ""Value"",
                    ""id"": ""bdc136dc-e51d-41d5-baa5-2492c2c8d649"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""P1HardDrop"",
                    ""type"": ""Button"",
                    ""id"": ""b8be0a5b-29cd-4214-b07a-810dc724d33f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1Hold"",
                    ""type"": ""Button"",
                    ""id"": ""358c4ece-1cbd-48a0-96fb-1987de9f3e74"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""d0c328c6-aa71-4b9c-b2c4-620a007b71fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""P2Move"",
                    ""type"": ""Value"",
                    ""id"": ""b3b1274b-2a8d-43e9-a240-232e0d65a820"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""P2HardDrop"",
                    ""type"": ""Button"",
                    ""id"": ""d0ffc85b-7961-48fb-920f-c5b802cca6c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2Hold"",
                    ""type"": ""Button"",
                    ""id"": ""aca48889-b467-46d0-bfe1-6f6e606bafbc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""65240396-9840-4f8e-8883-c933e634b50c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""P1Drop"",
                    ""type"": ""Button"",
                    ""id"": ""34fd9d9b-fdb3-494b-b539-bc9c6c1ea7e3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2Drop"",
                    ""type"": ""Button"",
                    ""id"": ""4bda79ea-51b8-4089-8e44-4b74065082d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""08330720-fbd2-4194-9337-c01e27a180e6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""40b8886b-20a8-4592-b46a-cbfa2da5c943"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""58034e3c-f98d-4bd5-9980-c4b7a0d2e010"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4b757de3-d033-45dc-b5f8-c018247afc9f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""11c9e3b3-30c0-488d-abf5-b2fda701f142"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""728bdf06-05d4-4a3f-951f-91add1f432ea"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1HardDrop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc256607-66da-48c4-b8e4-46d235d1aac1"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Hold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""5178c48f-e370-4eeb-9833-b6db692af304"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""380b90a3-7aa5-4254-b7dd-97ebc4fe4f80"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""03b203e4-24d7-4f80-8403-8b2f5cb59a13"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d88f7fe2-efae-4997-93e7-a6a9f08078a2"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""22dadc6e-368f-4e30-b444-89df8d1dbe5a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ad5a3ed2-def8-4f9e-8322-43691c97a75b"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2HardDrop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b74ac02a-2392-4df2-98ba-c978240a4571"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Hold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""5012ec82-18aa-4962-8992-ba924c4d5c70"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f4c5d996-3bfa-4f77-815c-32ca22f42dff"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""5b84f84a-6a3a-4193-ae0d-4511b044e5f2"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""b3e2a1da-3163-4a8e-8c37-0f6ae47dc03e"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""4b71604e-bb88-45d8-bd9d-7c73670bf942"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""03dee875-bdda-4dbe-b808-6fef909802ff"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""88ff2d85-81b0-4357-a69d-8dbe3c743189"",
                    ""path"": ""<Keyboard>/capsLock"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""497ccaff-38cc-422a-a65a-fbed49fa7b6f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Rebind"",
            ""id"": ""ab010c89-8742-41ca-b11d-993fda4cc9b9"",
            ""actions"": [
                {
                    ""name"": ""P1Move"",
                    ""type"": ""Value"",
                    ""id"": ""54a31992-620b-481b-8995-0d27cb54c2f1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""P1HardDrop"",
                    ""type"": ""Button"",
                    ""id"": ""a4a68058-559a-4b93-9f38-89d5545d2aff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1Hold"",
                    ""type"": ""Button"",
                    ""id"": ""8955a640-a7ac-4ce4-bf0a-9919eb261c0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""6d7d6a48-3687-4ce9-b679-acbf4a978748"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""P2Move"",
                    ""type"": ""Value"",
                    ""id"": ""31011910-83de-4f9e-9d4e-84ff1232a2ac"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""P2HardDrop"",
                    ""type"": ""Button"",
                    ""id"": ""58a3f5c2-bedb-4916-84d4-8c0673ddf01a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2Hold"",
                    ""type"": ""Button"",
                    ""id"": ""a98ff735-5b1b-4eb8-b072-d3fc800b736f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""527a4c51-2d95-4adc-8638-fa786e5b4c63"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c5320515-b1a6-46c7-93d1-1fdc773773fc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2bf381cc-5083-4250-8cb2-92450f73feb9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ffdf9099-f3c0-4c77-93eb-076797d0faf2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8706213b-8742-4e52-a45a-bca1953a5951"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""697496ac-f4c4-4f1e-8a80-0a865e7bfd69"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""95a32c04-d9f4-4354-97c6-531a7f942d68"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1HardDrop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3439e46-e652-4d3a-b574-1b3055d0d93b"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Hold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""327fa4fa-8f31-4f6e-be5b-611c96a26d01"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""821b3431-6213-411c-ae10-22daf08e1948"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1f1ea7bf-dc30-49e7-8a35-8affe59b4814"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ac116405-aaaa-44f3-86e8-4460c61fd838"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e19d1d20-d465-4a76-a50f-cd7a506d1516"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6e7159f8-46c1-4166-aee2-67b6879bdcb2"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2HardDrop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a280893b-5e7f-464a-97d8-44741d95a341"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Hold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""84e115d3-a3b5-46a6-ba69-54d6dc31a52d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""29299ad2-69c9-44ec-b443-d2a19b18e499"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""a28027e9-efd2-4deb-b3d1-0816d927250c"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""7daac174-d50f-469b-8de9-5f55dcf1a439"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9cd5d7b4-8fa5-4866-9429-03a83154d428"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""8e73af8d-ce5f-4340-bdf1-48a31aa6239f"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_P1Move = m_Player.FindAction("P1Move", throwIfNotFound: true);
        m_Player_P1HardDrop = m_Player.FindAction("P1HardDrop", throwIfNotFound: true);
        m_Player_P1Hold = m_Player.FindAction("P1Hold", throwIfNotFound: true);
        m_Player_P1Rotate = m_Player.FindAction("P1Rotate", throwIfNotFound: true);
        m_Player_P2Move = m_Player.FindAction("P2Move", throwIfNotFound: true);
        m_Player_P2HardDrop = m_Player.FindAction("P2HardDrop", throwIfNotFound: true);
        m_Player_P2Hold = m_Player.FindAction("P2Hold", throwIfNotFound: true);
        m_Player_P2Rotate = m_Player.FindAction("P2Rotate", throwIfNotFound: true);
        m_Player_P1Drop = m_Player.FindAction("P1Drop", throwIfNotFound: true);
        m_Player_P2Drop = m_Player.FindAction("P2Drop", throwIfNotFound: true);
        // Rebind
        m_Rebind = asset.FindActionMap("Rebind", throwIfNotFound: true);
        m_Rebind_P1Move = m_Rebind.FindAction("P1Move", throwIfNotFound: true);
        m_Rebind_P1HardDrop = m_Rebind.FindAction("P1HardDrop", throwIfNotFound: true);
        m_Rebind_P1Hold = m_Rebind.FindAction("P1Hold", throwIfNotFound: true);
        m_Rebind_P1Rotate = m_Rebind.FindAction("P1Rotate", throwIfNotFound: true);
        m_Rebind_P2Move = m_Rebind.FindAction("P2Move", throwIfNotFound: true);
        m_Rebind_P2HardDrop = m_Rebind.FindAction("P2HardDrop", throwIfNotFound: true);
        m_Rebind_P2Hold = m_Rebind.FindAction("P2Hold", throwIfNotFound: true);
        m_Rebind_P2Rotate = m_Rebind.FindAction("P2Rotate", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_P1Move;
    private readonly InputAction m_Player_P1HardDrop;
    private readonly InputAction m_Player_P1Hold;
    private readonly InputAction m_Player_P1Rotate;
    private readonly InputAction m_Player_P2Move;
    private readonly InputAction m_Player_P2HardDrop;
    private readonly InputAction m_Player_P2Hold;
    private readonly InputAction m_Player_P2Rotate;
    private readonly InputAction m_Player_P1Drop;
    private readonly InputAction m_Player_P2Drop;
    public struct PlayerActions
    {
        private @PlayerInput m_Wrapper;
        public PlayerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @P1Move => m_Wrapper.m_Player_P1Move;
        public InputAction @P1HardDrop => m_Wrapper.m_Player_P1HardDrop;
        public InputAction @P1Hold => m_Wrapper.m_Player_P1Hold;
        public InputAction @P1Rotate => m_Wrapper.m_Player_P1Rotate;
        public InputAction @P2Move => m_Wrapper.m_Player_P2Move;
        public InputAction @P2HardDrop => m_Wrapper.m_Player_P2HardDrop;
        public InputAction @P2Hold => m_Wrapper.m_Player_P2Hold;
        public InputAction @P2Rotate => m_Wrapper.m_Player_P2Rotate;
        public InputAction @P1Drop => m_Wrapper.m_Player_P1Drop;
        public InputAction @P2Drop => m_Wrapper.m_Player_P2Drop;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @P1Move.started += instance.OnP1Move;
            @P1Move.performed += instance.OnP1Move;
            @P1Move.canceled += instance.OnP1Move;
            @P1HardDrop.started += instance.OnP1HardDrop;
            @P1HardDrop.performed += instance.OnP1HardDrop;
            @P1HardDrop.canceled += instance.OnP1HardDrop;
            @P1Hold.started += instance.OnP1Hold;
            @P1Hold.performed += instance.OnP1Hold;
            @P1Hold.canceled += instance.OnP1Hold;
            @P1Rotate.started += instance.OnP1Rotate;
            @P1Rotate.performed += instance.OnP1Rotate;
            @P1Rotate.canceled += instance.OnP1Rotate;
            @P2Move.started += instance.OnP2Move;
            @P2Move.performed += instance.OnP2Move;
            @P2Move.canceled += instance.OnP2Move;
            @P2HardDrop.started += instance.OnP2HardDrop;
            @P2HardDrop.performed += instance.OnP2HardDrop;
            @P2HardDrop.canceled += instance.OnP2HardDrop;
            @P2Hold.started += instance.OnP2Hold;
            @P2Hold.performed += instance.OnP2Hold;
            @P2Hold.canceled += instance.OnP2Hold;
            @P2Rotate.started += instance.OnP2Rotate;
            @P2Rotate.performed += instance.OnP2Rotate;
            @P2Rotate.canceled += instance.OnP2Rotate;
            @P1Drop.started += instance.OnP1Drop;
            @P1Drop.performed += instance.OnP1Drop;
            @P1Drop.canceled += instance.OnP1Drop;
            @P2Drop.started += instance.OnP2Drop;
            @P2Drop.performed += instance.OnP2Drop;
            @P2Drop.canceled += instance.OnP2Drop;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @P1Move.started -= instance.OnP1Move;
            @P1Move.performed -= instance.OnP1Move;
            @P1Move.canceled -= instance.OnP1Move;
            @P1HardDrop.started -= instance.OnP1HardDrop;
            @P1HardDrop.performed -= instance.OnP1HardDrop;
            @P1HardDrop.canceled -= instance.OnP1HardDrop;
            @P1Hold.started -= instance.OnP1Hold;
            @P1Hold.performed -= instance.OnP1Hold;
            @P1Hold.canceled -= instance.OnP1Hold;
            @P1Rotate.started -= instance.OnP1Rotate;
            @P1Rotate.performed -= instance.OnP1Rotate;
            @P1Rotate.canceled -= instance.OnP1Rotate;
            @P2Move.started -= instance.OnP2Move;
            @P2Move.performed -= instance.OnP2Move;
            @P2Move.canceled -= instance.OnP2Move;
            @P2HardDrop.started -= instance.OnP2HardDrop;
            @P2HardDrop.performed -= instance.OnP2HardDrop;
            @P2HardDrop.canceled -= instance.OnP2HardDrop;
            @P2Hold.started -= instance.OnP2Hold;
            @P2Hold.performed -= instance.OnP2Hold;
            @P2Hold.canceled -= instance.OnP2Hold;
            @P2Rotate.started -= instance.OnP2Rotate;
            @P2Rotate.performed -= instance.OnP2Rotate;
            @P2Rotate.canceled -= instance.OnP2Rotate;
            @P1Drop.started -= instance.OnP1Drop;
            @P1Drop.performed -= instance.OnP1Drop;
            @P1Drop.canceled -= instance.OnP1Drop;
            @P2Drop.started -= instance.OnP2Drop;
            @P2Drop.performed -= instance.OnP2Drop;
            @P2Drop.canceled -= instance.OnP2Drop;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Rebind
    private readonly InputActionMap m_Rebind;
    private List<IRebindActions> m_RebindActionsCallbackInterfaces = new List<IRebindActions>();
    private readonly InputAction m_Rebind_P1Move;
    private readonly InputAction m_Rebind_P1HardDrop;
    private readonly InputAction m_Rebind_P1Hold;
    private readonly InputAction m_Rebind_P1Rotate;
    private readonly InputAction m_Rebind_P2Move;
    private readonly InputAction m_Rebind_P2HardDrop;
    private readonly InputAction m_Rebind_P2Hold;
    private readonly InputAction m_Rebind_P2Rotate;
    public struct RebindActions
    {
        private @PlayerInput m_Wrapper;
        public RebindActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @P1Move => m_Wrapper.m_Rebind_P1Move;
        public InputAction @P1HardDrop => m_Wrapper.m_Rebind_P1HardDrop;
        public InputAction @P1Hold => m_Wrapper.m_Rebind_P1Hold;
        public InputAction @P1Rotate => m_Wrapper.m_Rebind_P1Rotate;
        public InputAction @P2Move => m_Wrapper.m_Rebind_P2Move;
        public InputAction @P2HardDrop => m_Wrapper.m_Rebind_P2HardDrop;
        public InputAction @P2Hold => m_Wrapper.m_Rebind_P2Hold;
        public InputAction @P2Rotate => m_Wrapper.m_Rebind_P2Rotate;
        public InputActionMap Get() { return m_Wrapper.m_Rebind; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RebindActions set) { return set.Get(); }
        public void AddCallbacks(IRebindActions instance)
        {
            if (instance == null || m_Wrapper.m_RebindActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RebindActionsCallbackInterfaces.Add(instance);
            @P1Move.started += instance.OnP1Move;
            @P1Move.performed += instance.OnP1Move;
            @P1Move.canceled += instance.OnP1Move;
            @P1HardDrop.started += instance.OnP1HardDrop;
            @P1HardDrop.performed += instance.OnP1HardDrop;
            @P1HardDrop.canceled += instance.OnP1HardDrop;
            @P1Hold.started += instance.OnP1Hold;
            @P1Hold.performed += instance.OnP1Hold;
            @P1Hold.canceled += instance.OnP1Hold;
            @P1Rotate.started += instance.OnP1Rotate;
            @P1Rotate.performed += instance.OnP1Rotate;
            @P1Rotate.canceled += instance.OnP1Rotate;
            @P2Move.started += instance.OnP2Move;
            @P2Move.performed += instance.OnP2Move;
            @P2Move.canceled += instance.OnP2Move;
            @P2HardDrop.started += instance.OnP2HardDrop;
            @P2HardDrop.performed += instance.OnP2HardDrop;
            @P2HardDrop.canceled += instance.OnP2HardDrop;
            @P2Hold.started += instance.OnP2Hold;
            @P2Hold.performed += instance.OnP2Hold;
            @P2Hold.canceled += instance.OnP2Hold;
            @P2Rotate.started += instance.OnP2Rotate;
            @P2Rotate.performed += instance.OnP2Rotate;
            @P2Rotate.canceled += instance.OnP2Rotate;
        }

        private void UnregisterCallbacks(IRebindActions instance)
        {
            @P1Move.started -= instance.OnP1Move;
            @P1Move.performed -= instance.OnP1Move;
            @P1Move.canceled -= instance.OnP1Move;
            @P1HardDrop.started -= instance.OnP1HardDrop;
            @P1HardDrop.performed -= instance.OnP1HardDrop;
            @P1HardDrop.canceled -= instance.OnP1HardDrop;
            @P1Hold.started -= instance.OnP1Hold;
            @P1Hold.performed -= instance.OnP1Hold;
            @P1Hold.canceled -= instance.OnP1Hold;
            @P1Rotate.started -= instance.OnP1Rotate;
            @P1Rotate.performed -= instance.OnP1Rotate;
            @P1Rotate.canceled -= instance.OnP1Rotate;
            @P2Move.started -= instance.OnP2Move;
            @P2Move.performed -= instance.OnP2Move;
            @P2Move.canceled -= instance.OnP2Move;
            @P2HardDrop.started -= instance.OnP2HardDrop;
            @P2HardDrop.performed -= instance.OnP2HardDrop;
            @P2HardDrop.canceled -= instance.OnP2HardDrop;
            @P2Hold.started -= instance.OnP2Hold;
            @P2Hold.performed -= instance.OnP2Hold;
            @P2Hold.canceled -= instance.OnP2Hold;
            @P2Rotate.started -= instance.OnP2Rotate;
            @P2Rotate.performed -= instance.OnP2Rotate;
            @P2Rotate.canceled -= instance.OnP2Rotate;
        }

        public void RemoveCallbacks(IRebindActions instance)
        {
            if (m_Wrapper.m_RebindActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRebindActions instance)
        {
            foreach (var item in m_Wrapper.m_RebindActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RebindActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RebindActions @Rebind => new RebindActions(this);
    public interface IPlayerActions
    {
        void OnP1Move(InputAction.CallbackContext context);
        void OnP1HardDrop(InputAction.CallbackContext context);
        void OnP1Hold(InputAction.CallbackContext context);
        void OnP1Rotate(InputAction.CallbackContext context);
        void OnP2Move(InputAction.CallbackContext context);
        void OnP2HardDrop(InputAction.CallbackContext context);
        void OnP2Hold(InputAction.CallbackContext context);
        void OnP2Rotate(InputAction.CallbackContext context);
        void OnP1Drop(InputAction.CallbackContext context);
        void OnP2Drop(InputAction.CallbackContext context);
    }
    public interface IRebindActions
    {
        void OnP1Move(InputAction.CallbackContext context);
        void OnP1HardDrop(InputAction.CallbackContext context);
        void OnP1Hold(InputAction.CallbackContext context);
        void OnP1Rotate(InputAction.CallbackContext context);
        void OnP2Move(InputAction.CallbackContext context);
        void OnP2HardDrop(InputAction.CallbackContext context);
        void OnP2Hold(InputAction.CallbackContext context);
        void OnP2Rotate(InputAction.CallbackContext context);
    }
}
